public with sharing virtual class LineBase {
	public static String LINE_OAUTH_ACCESSTOKEN = 'https://api.line.me/v2/oauth/accessToken';
	public static String LINE_GET_PROFILE_URI = 'https://api.line.me/v2/profile';
	public static String CLIEN_ID = '1498466312';
	public static String CLIEN_SECRET ='970e4324dfe2ca3e8d1885ba91f9cffb';
	public static String REDIRECT_URL = 'https%3A%2F%2Fhayai-study2017-developer-edition.ap4.force.com%2FLinePage';
}